// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sampleWebApp.Models;

public partial class BookAuthor
{
    public int AuthorId { get; set; }

    public int BookId { get; set; }

    public byte? AuthorOrder { get; set; }

    public int? RoyalityPercentage { get; set; }

    public virtual Author Author { get; set; }

    public virtual Book Book { get; set; }
}