// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sampleWebApp.Models;

public partial class Job
{
    public short JobId { get; set; }

    public string JobDesc { get; set; }
}