// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sampleWebApp.Models;

public partial class User
{
    public int UserId { get; set; }

    public string EmailAddress { get; set; }

    public string Password { get; set; }

    public string Source { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public short RoleId { get; set; }

    public int PubId { get; set; }

    public DateTime? HireDate { get; set; }

    public virtual Publisher Pub { get; set; }

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    public virtual Role Role { get; set; }
}